SQL_CREATE_TABLE_LINKS = '''
CREATE TABLE IF NOT EXISTS links
(
    id SERIAL PRIMARY KEY,
    "from" INTEGER
        CONSTRAINT pages_from_fk REFERENCES pages ON UPDATE CASCADE ON DELETE CASCADE,
    "to" INTEGER
        CONSTRAINT pages_to_fk REFERENCES pages ON UPDATE CASCADE ON DELETE CASCADE
)
'''

SQL_CREATE_TABLE_PAGES = '''
CREATE TABLE IF NOT EXISTS pages
(
    id SERIAL PRIMARY KEY,
    url VARCHAR(2048) UNIQUE,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    code INTEGER DEFAULT NULL
)
'''

SQL_CREATE_FUNC_LINKS_DEPTH = '''
CREATE OR REPLACE FUNCTION depth(links) 
RETURNS INTEGER AS $$
BEGIN
    SELECT CASE
        WHEN ($1."to" IS NULL) THEN 0
        ELSE 1 + (SELECT * FROM links WHERE "to" = $1."from").depth
    END;
END;$$
LANGUAGE SQL
'''

SQL_CREATE_FUNC_PAGES_DEPTH = '''
CREATE OR REPLACE FUNCTION depth(pages) 
RETURNS INTEGER AS $$
BEGIN
    SELECT MIN(depth()) from links WHERE "to" = $1.id;
END;$$
LANGUAGE SQL
'''
